name: Nasa Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ["4.4", "7.0"]
    name: Node ${{ matrix.node-version }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@v1.10.0
        with: 
          mongodb-version: {{matrix.mongodb-version}} 
               
      - name: Install client
        working-directory: client
        run: npm install
      
      - name: Install server
        working-directory: server
        run: npm install

      - name: Build
        working-directory: client
        run: npm run build
      
      - name: Test
        run: npm run test
