name: NASA CI 
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main] 


jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 18.18.0
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"
      - run: npm install
      - run: npm run build --prefix client
    